
import os
from datetime import datetime
from triage.explain import explain_alert
from utils.flatten import flatten_dict



EXPORT_DIR = "exports"
os.makedirs(EXPORT_DIR, exist_ok=True)

HTML_HEAD = """
<!DOCTYPE html>
<html lang=\"en\">
<head>
  <meta charset=\"UTF-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
  <title>SOCscribe Export</title>
  <style>
    body { font-family: Arial, sans-serif; background: #f5f5f5; color: #222; padding: 2em; }
    summary { cursor: pointer; font-weight: bold; margin-top: 1em; }
    details { background: #fff; border-radius: 6px; margin-bottom: 1em; padding: 1em; box-shadow: 0 2px 6px rgba(0,0,0,0.1); }
    .meta { margin: 0.5em 0; font-size: 0.9em; color: #666; }
    .field { margin: 0.5em 0; }
    .field span { display: block; }
    .field .key { font-weight: bold; }
    .field .value { margin-left: 1em; }
    .footer { margin-top: 3em; font-size: 0.8em; color: #aaa; }
  </style>
</head>
<body>
  <h1>SOCscribe - Alert Breakdown</h1>
"""

HTML_FOOT = """
  <div class=\"footer\">Generated by SOCscribe</div>
</body>
</html>
"""

def export_alerts(alerts):
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = os.path.join(EXPORT_DIR, f"socscribe_export_{timestamp}.html")

    with open(filename, 'w') as f:
        f.write(HTML_HEAD)

        for alert in alerts:
            rule = alert.get("rule", {})
            description = rule.get("description", "[No description]")
            alert_time = alert.get("timestamp", "[No timestamp]")
            alert_id = alert.get("id", "[No ID]")

            f.write(f"<details><summary>{description}</summary>")
            f.write(f"<div class='meta'>🆔 Alert ID: {alert_id}<br>🕒 Time: {alert_time}</div>")

            flat = flatten_dict(alert)
            for key, value in flat.items():
                from triage.field_explanations import get_field_explanation
                explanation = get_field_explanation(key)
                f.write(f"<div class='field'><span class='key'>{key}:</span><span class='value'>{value}</span><span><em>{explanation}</em></span></div>")

            f.write("<div class='field'><strong>🎯 Recommended Actions</strong><ul>")
            f.write("<li>No specific playbook found for this rule.</li>")
            f.write("<li>Review logs, check user/process/IP behavior manually.</li>")
            f.write("</ul><strong>🧑‍💼 Who Should Investigate This?</strong><p>Start with a Tier 1 SOC Analyst. Escalate if needed.</p></div>")

            f.write("</details>")

        f.write(HTML_FOOT)

    print(f"[+] Exported HTML report to: {filename}")
