field_explanations = {
  "data.arch": "System architecture (e.g., x86_64, arm). Useful for knowing what binaries it can run. This field may not be critical in all cases, but helps with context.",
  "data.dpkg_status": "Status of a Debian package on the system \u2014 used in vulnerability assessments. If this shows 'failed' or 'denied', you may need deeper investigation.",
  "data.dstuser": "Destination user for a connection or process action \u2014 helpful in lateral movement detection. Always check if this is a known admin or strange user.",
  "data.extra": "Extra data captured for the alert. May contain contextual or custom fields. This field may not be critical in all cases, but helps with context.",
  "data.package": "Software package involved in the event. Useful in software inventory or patch checks. This field may not be critical in all cases, but helps with context.",
  "data.sca": "Security Configuration Assessment data root. Contains scan results and metadata. This field may not be critical in all cases, but helps with context.",
  "data.sca.check": "Details about a specific security configuration check. This field may not be critical in all cases, but helps with context.",
  "data.sca.check.command": "Command used to run the configuration check on the system. This field may not be critical in all cases, but helps with context.",
  "data.sca.check.compliance.cis": "Whether this check maps to CIS (Center for Internet Security) standards. Relevant for audit and regulatory enforcement \u2014 take note if failed.",
  "data.sca.check.compliance.gdpr_V": "GDPR compliance category mapping \u2014 personal data protection. Relevant for audit and regulatory enforcement \u2014 take note if failed.",
  "data.sca.check.compliance.gpg_13": "GPG13 compliance for UK government security standards. Relevant for audit and regulatory enforcement \u2014 take note if failed.",
  "data.sca.check.compliance.gpgl3": "Duplicate of gpg_13 \u2014 may be a parsing or normalization issue. Relevant for audit and regulatory enforcement \u2014 take note if failed.",
  "data.sca.check.compliance.hipaa": "Maps to HIPAA compliance \u2014 especially important in healthcare systems. Relevant for audit and regulatory enforcement \u2014 take note if failed.",
  "data.sca.check.compliance.nist_800_53": "Maps to NIST 800-53 controls \u2014 a U.S. government security baseline. Relevant for audit and regulatory enforcement \u2014 take note if failed.",
  "data.sca.check.compliance.pel_dss": "PCI DSS compliance mapping \u2014 protects cardholder data. Relevant for audit and regulatory enforcement \u2014 take note if failed.",
  "data.sca.check.compliance.tse": "SOC2 TSC compliance mapping \u2014 for cloud and SaaS services. Relevant for audit and regulatory enforcement \u2014 take note if failed.",
  "data.sca.check.description": "Description of what the config check is testing (e.g., password policy). Read this carefully \u2014 often tells you what the alert is really about.",
  "data.sca.check.previous": "Previous value of a config before the current scan \u2014 useful for tracking drift. This field may not be critical in all cases, but helps with context.",
  "data.sca.check.rationale": "Reason why this check matters \u2014 good for audit documentation. This field may not be critical in all cases, but helps with context.",
  "data.sca.check.reason": "Explanation for the check result (why it passed or failed). This field may not be critical in all cases, but helps with context.",
  "data.sca.check.references": "References to standards or docs that support this check. This field may not be critical in all cases, but helps with context.",
  "data.sca.check.registry": "Registry key involved in the configuration check (for Windows). Serious if this shows sensitive registry paths like Run, RunOnce, or services.",
  "data.sca.check.remediation": "Suggested fix or hardening action for the failed check. You should apply this fix to harden the system.",
  "data.sca.checkcttle": "Likely a typo or malformed field from parsing. This field may not be critical in all cases, but helps with context.",
  "data.sca.checkid": "Unique ID of the configuration check. Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "data.sca.description": "Overall description of the SCA scan or policy. Read this carefully \u2014 often tells you what the alert is really about.",
  "data.sca.invalid": "Marks whether a check was invalid (couldn\u2019t run properly). Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "data.sca.passed": "Boolean flag showing whether this check passed. This field may not be critical in all cases, but helps with context.",
  "data.sca.policy": "The name of the SCA policy applied (e.g., CIS Ubuntu 20.04). Relevant for audit and regulatory enforcement \u2014 take note if failed.",
  "data.sca.scan_id": "ID of the full scan session. Used to group checks from the same run. Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "data.sca.total_checks": "Total number of configuration checks run in this scan. This field may not be critical in all cases, but helps with context.",
  "data.sca.type": "Type of the SCA check (e.g., script, registry). This field may not be critical in all cases, but helps with context.",
  "data.srcport": "Source port of a connection. Helps detect unusual outbound behavior. This field may not be critical in all cases, but helps with context.",
  "data.uid": "User ID that initiated the event or alert. Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "data.version": "Version of a file or application. Useful for checking patch levels. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata": "Container for all Windows Event log fields. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.accountName": "Username involved in the event. Always check if this is a known admin or strange user.",
  "data.win.eventdata.attachedFiles": "Any file(s) attached to the event (e.g., in Office macros). This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.binary": "Indicates whether the event carried a binary payload. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.bucket": "Used for correlation or grouping by category (custom use). This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.bucketType": "Type of correlation bucket this event belongs to. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.cabGuld": "GUID related to a CAB archive involved in the event. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.cabld": "Identifier for CAB installation package or update. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.commandLine": "Full command line used \u2014 great for detecting attacks like PowerShell misuse. Review this carefully \u2014 attackers often abuse PowerShell or unusual binaries.",
  "data.win.eventdata.company": "Company field from the binary metadata. Check for suspicious vendors. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.context": "Security or execution context of the process (e.g., SYSTEM vs User). This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.creationUtcTime": "UTC time when the event or process was created. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.currentDirectory": "The working directory from which the command was run. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.data": "Raw data blob attached to the event. Use in forensic cases. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.description": "Text description of the file or process. Can be faked by malware. Read this carefully \u2014 often tells you what the alert is really about.",
  "data.win.eventdata.details": "Extra details about the event \u2014 may include parameters or state info. Read this carefully \u2014 often tells you what the alert is really about.",
  "data.win.eventdata.elevatedToken": "True if the process was running with elevated (admin) privileges. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.errorCode": "Error code associated with the event \u2014 useful for troubleshooting. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.eventName": "Name of the Windows event \u2014 shows what action was taken. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.eventType": "Type/category of event \u2014 helps classify what happened. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.extraInfo": "Additional notes or metadata \u2014 varies by event type. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.fileVersion": "Version of the file involved \u2014 helps detect tampering or old versions. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.hashedBucket": "Hash used to categorize the event in a group or bucket. If this hash is unknown or does not match the original, it may be malware.",
  "data.win.eventdata.hashes": "One or more hash values (MD5/SHA1/SHA256) of the file \u2014 used to check for malware. If this hash is unknown or does not match the original, it may be malware.",
  "data.win.eventdata.hResult": "Windows result code \u2014 usually indicates success or failure. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.image": "Full path of the file or binary that was executed. Review this carefully \u2014 attackers often abuse PowerShell or unusual binaries.",
  "data.win.eventdata.imagePath": "Folder path where the executable is located. Review this carefully \u2014 attackers often abuse PowerShell or unusual binaries.",
  "data.win.eventdata.impersonationLevel": "Level of user impersonation \u2014 higher levels can indicate privilege abuse. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.integrityLevel": "Process security level \u2014 low, medium, high. Low may mean sandboxed. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.ipAddress": "IP address involved in the event \u2014 check for external or strange IPs. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.ipPort": "Network port used \u2014 may indicate protocol or service type. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.keyLength": "Length of encryption key used \u2014 relevant for secure logins or sessions. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.logonGuid": "Unique ID for the logon session \u2014 useful for tracking lateral movement. Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "data.win.eventdata.logonId": "Numeric ID for user login \u2014 pairs with logonType to track sessions. Helps track user sessions \u2014 important during lateral movement.",
  "data.win.eventdata.logonProcessName": "Name of the logon process (e.g., winlogon, sshd). This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.logonType": "Type of logon (e.g., 2 = local, 3 = network, 10 = RDP). Pay attention if this is '10' (RDP) or '3' (network) \u2014 often used in attacks.",
  "data.win.eventdata.messageText": "The full text message from the Windows event. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.method": "Authentication method or action used (e.g., Negotiate, NTLM). This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.newTime": "Updated time value \u2014 used in time change events. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.originalFileName": "Original name embedded in the file \u2014 can detect renamed malware. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.p1": "First generic parameter in the event. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.p2": "Second parameter (often registry value, SID, or config item). This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.p3": "Third parameter \u2014 meaning depends on event type. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.p4": "Fourth parameter \u2014 additional context. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.p5": "Fifth parameter \u2014 used for extra technical detail. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.param1": "Parameter 1 \u2014 varies by log type, often user or filename. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.param2": "Parameter 2 \u2014 can be logon type, reason, or IP. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.param3": "Parameter 3 \u2014 continues describing the event. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.param4": "Parameter 4 \u2014 more event info. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.parentCommandLine": "Command used to launch the parent process. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.parentImage": "Path to the parent executable that launched this one. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.parentProcessGuid": "GUID of the parent process \u2014 helps chain events together. Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "data.win.eventdata.parentProcessId": "Process ID of the parent \u2014 helps identify root cause of process trees. Useful to trace how a suspicious process started.",
  "data.win.eventdata.parentUser": "User who launched the parent process. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.previousTime": "Old timestamp \u2014 used when a time is updated. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.processGuid": "Unique ID for the running process \u2014 stable across logs. Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "data.win.eventdata.processId": "Numeric ID of the running process. Useful to trace how a suspicious process started.",
  "data.win.eventdata.reportId": "ID for the report that contains this event. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.reportStatus": "Current status of the event report (e.g., complete, error). This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.response": "Response taken (e.g., blocked, allowed) \u2014 common in EDR logs. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.ruleName": "Name of the detection rule that triggered this alert. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.serviceGuid": "Unique ID for the Windows service involved. Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "data.win.eventdata.serviceName": "Name of the service involved in this event. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.serviceType": "Type of Windows service (kernel, driver, user-mode). This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.stage": "Stage of execution or detection (e.g., Pre, Post). This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.startType": "How the service starts: 2 = Auto, 3 = Manual, 4 = Disabled. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.storePath": "Filesystem path used to store the data or file. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.subjectDomainName": "Domain of the user who initiated the action. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.subjectLogonId": "Logon session ID of the initiating user. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.subjectUserName": "Username of the person who triggered the action. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.subjectUserSid": "SID (security identifier) of the user who took the action. Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "data.win.eventdata.targetDomainName": "Domain of the user or object being affected. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.targetFileName": "Name of the file targeted in this action. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.targetLinkedLogonId": "Linked session ID (useful for RDP or impersonation). This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.targetObject": "Registry key, file, or target being modified or accessed. Serious if this shows sensitive registry paths like Run, RunOnce, or services.",
  "data.win.eventdata.targetUserName": "User being affected in the event. Always check if this is a known admin or strange user.",
  "data.win.eventdata.targetUserSid": "Security identifier of the target user. Always check if this is a known admin or strange user.",
  "data.win.eventdata.terminalSessionId": "ID of the user's terminal session (local, remote). This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.updateGuid": "GUID of the Windows update being referenced. Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "data.win.eventdata.updateRevisionNumber": "Revision number of the Windows update. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.updateTitle": "Title or name of the Windows update. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.url": "URL accessed or embedded in the event. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.user": "User involved \u2014 either actor or target. Always check if this is a known admin or strange user.",
  "data.win.eventdata.utcTime": "Coordinated UTC timestamp \u2014 most accurate for correlation. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.virtualAccount": "True if the action was run by a virtual service account. This field may not be critical in all cases, but helps with context.",
  "data.win.eventdata.workstationName": "Name of the machine where this event was recorded. This field may not be critical in all cases, but helps with context.",
  "syscheck.changed_attributes": "List of file attributes that were changed. This field may not be critical in all cases, but helps with context.",
  "syscheck.event": "Type of file integrity event (e.g., modified, deleted). This field may not be critical in all cases, but helps with context.",
  "syscheck.gid_after": "Group ID of the file after the change. Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "syscheck.gname_after": "Group name after the change. This field may not be critical in all cases, but helps with context.",
  "syscheck.inode_after": "Filesystem inode number after the change. This field may not be critical in all cases, but helps with context.",
  "syscheck.inode_before": "Inode before the change \u2014 helps detect file replacement. This field may not be critical in all cases, but helps with context.",
  "syscheck.md5_after": "MD5 hash after the change \u2014 useful for integrity check. This field may not be critical in all cases, but helps with context.",
  "syscheck.md5_before": "MD5 hash before change \u2014 compare to detect tampering. This field may not be critical in all cases, but helps with context.",
  "syscheck.mode": "File permissions in numeric mode (e.g., 755). This field may not be critical in all cases, but helps with context.",
  "syscheck.mtime_after": "Modification time after change. Always correlate with user activity \u2014 timing is key in attack chains.",
  "syscheck.mtime_before": "Modification time before change. Always correlate with user activity \u2014 timing is key in attack chains.",
  "syscheck.path": "Full file path of the monitored file. This field may not be critical in all cases, but helps with context.",
  "syscheck.perm_after": "Permissions in text form (e.g., rwxr-xr-x) after change. This field may not be critical in all cases, but helps with context.",
  "syscheck.sha1_after": "SHA1 hash after change. This field may not be critical in all cases, but helps with context.",
  "syscheck.sha1_before": "SHA1 hash before change. This field may not be critical in all cases, but helps with context.",
  "syscheck.sha256_after": "SHA256 hash after change \u2014 stronger for tamper detection. If this hash is unknown or does not match the original, it may be malware.",
  "syscheck.sha256_before": "SHA256 before \u2014 compare for change validation. If this hash is unknown or does not match the original, it may be malware.",
  "syscheck.size_after": "File size after modification. This field may not be critical in all cases, but helps with context.",
  "syscheck.size_before": "File size before modification. This field may not be critical in all cases, but helps with context.",
  "syscheck.uid_after": "User ID of the file after change. Useful for searching related events \u2014 look for repeated suspicious IDs.",
  "syscheck.uname_after": "Username of the file owner after change. This field may not be critical in all cases, but helps with context.",
  "timestamp": "The time this alert or log was generated \u2014 key for correlation. Always correlate with user activity \u2014 timing is key in attack chains.",
  "data.win.eventdata.detalls": "Extra details about the event \u2014 may include parameters or state info. Read this carefully \u2014 often tells you what the alert is really about. (Corrected from typo field.)",
  "data.win.eventdata.extrainto": "Additional notes or metadata \u2014 varies by event type. This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "data.win.eventdata.fleVersion": "Version of the file involved \u2014 helps detect tampering or old versions. This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "data.win.eventdata.logonid": "Unique ID for the logon session \u2014 useful for tracking lateral movement. Useful for searching related events \u2014 look for repeated suspicious IDs. (Corrected from typo field.)",
  "data.win.eventdata.parentProcessid": "GUID of the parent process \u2014 helps chain events together. Useful for searching related events \u2014 look for repeated suspicious IDs. (Corrected from typo field.)",
  "data.win.eventdata.parentimage": "Path to the parent executable that launched this one. This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "data.win.eventdata.processName": "Numeric ID of the running process. Useful to trace how a suspicious process started. (Corrected from typo field.)",
  "data.win.eventdata.processid": "Unique ID for the running process \u2014 stable across logs. Useful for searching related events \u2014 look for repeated suspicious IDs. (Corrected from typo field.)",
  "data.win.eventdata.processld": "Numeric ID of the running process. Useful to trace how a suspicious process started. (Corrected from typo field.)",
  "data.win.eventdata.product": "Network port used \u2014 may indicate protocol or service type. This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "data.win.eventdata.reportid": "ID for the report that contains this event. This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "data.win.eventdata.subjectLogonid": "Logon session ID of the initiating user. This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "data.win.eventdata.targetLinkedLogonld": "Linked session ID (useful for RDP or impersonation). This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "data.win.eventdata.targetLogonid": "Linked session ID (useful for RDP or impersonation). This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "data.win.eventdata.targetfilename": "Name of the file targeted in this action. This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "data.win.eventdata.terminalSessionld": "ID of the user's terminal session (local, remote). This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "data.win.eventdata.updateRevisionNumber_": "Revision number of the Windows update. This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "syscheck.gld_after": "Group ID of the file after the change. Useful for searching related events \u2014 look for repeated suspicious IDs. (Corrected from typo field.)",
  "syscheck.inode": "File permissions in numeric mode (e.g., 755). This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "syscheck.mtime": "Modification time after change. Always correlate with user activity \u2014 timing is key in attack chains. (Corrected from typo field.)",
  "syscheck.sha256": "SHA256 hash after change \u2014 stronger for tamper detection. If this hash is unknown or does not match the original, it may be malware. (Corrected from typo field.)",
  "syscheck.shal_after": "SHA1 hash after change. This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "syscheck.shal_before": "SHA1 hash before change. This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "syscheck.size": "File size after modification. This field may not be critical in all cases, but helps with context. (Corrected from typo field.)",
  "syscheck.uld_after": "User ID of the file after change. Useful for searching related events \u2014 look for repeated suspicious IDs. (Corrected from typo field.)",
  "aata.ievel": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.eventdata.rechecking": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.channel": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.computer": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.evel": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.eventRecordlD": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.eventSourceName": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.eventiD": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.message": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.opcode": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.processiD": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.providerGuid": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.systemTime": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.threadID": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "data.win.system.version": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "datasca.file": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "datasca.score": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "decoder.parent": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "predecoder.program_name": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.fireatimes": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.gp913": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.groups": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.hipaa": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.info": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.mail": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.mitre.id": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.mitre.tactic": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.mitre.technique": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.nist_800_53": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.pei_dss": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "rule.tse": "No specific explanation available. May be informational or custom field. Review if context looks suspicious.",
  "syscheck.changed": "No specific explanation available. May be informational or custom field. Review if context looks suspicious."
}

def get_field_explanation(field_name):
    return field_explanations.get(field_name, "No explanation available for this field yet.")
