field_explanations = {
    # AGENT DETAILS
    "agent.id": "ID of the endpoint system that triggered the alert. Helps track device history.",
    "agent.name": "Name of the system (hostname). Useful for identifying which machine was involved.",
    "agent.ip": "IP address of the system. Watch for public or unknown internal addresses.",

    # BASIC ALERT INFO
    "timestamp": "When the alert was generated. Helps line up with user activity or incidents.",
    "id": "Unique alert identifier. Use it to search in dashboards or correlate with other alerts.",
    "manager.name": "The Wazuh server that received this alert. Usually your SIEM node.",
    "decoder.name": "The log decoder used to understand the original raw data.",
    "location": "Source of the alert, such as sysmon, auditd, or custom log.",
    "input.type": "Type of log input (logcollector, syscheck, etc).",
    "full_log": "The raw log message before parsing. Useful for manual analysis.",

    # RULE METADATA
    "rule.id": "The rule ID that triggered this alert.",
    "rule.level": "Severity level (0–15). 0–3 = Low, 4–7 = Medium, 8+ = High.",
    "rule.description": "What triggered this alert. Focus here first.",
    "rule.groups": "Tags about the alert (e.g., 'malware', 'auth_failed').",
    "rule.firedtimes": "How often this rule was triggered. High numbers mean frequent activity.",
    "rule.mail": "Whether this alert is configured to send an email.",
    "rule.gdpr": "Indicates GDPR compliance scope.",
    "rule.hipaa": "Indicates HIPAA compliance scope (health data).",
    "rule.pci_dss": "PCI compliance mapping (cardholder data protection).",
    "rule.nist_800_53": "NIST compliance mapping (standardized controls).",
    "rule.tsc": "SOC2 audit framework category.",
    "rule.mitre.id": "MITRE ATT&CK technique ID (e.g., T1059). Learn these.",
    "rule.mitre.tactic": "MITRE goal (e.g., Execution, Persistence). Explains attacker intention.",
    "rule.mitre.technique": "How the attacker tried to reach their goal.",

    # SCA (SECURITY CONFIG ASSESSMENTS)
    "data.sca.check.command": "The command that was run to check this system setting.",
    "data.sca.check.compliance.cis": "Indicates CIS benchmark relevance.",
    "data.sca.check.compliance.cis_csc": "Legacy compliance mapping (CIS).",
    "data.sca.check.compliance.gdpr_IV": "Mapping to GDPR article IV (privacy rules).",
    "data.sca.check.compliance.gpg_13": "UK's government cyber guideline mapping.",
    "data.sca.check.compliance.hipaa": "Privacy or healthcare related compliance flag.",
    "data.sca.check.compliance.nist_800_53": "US government compliance standard.",
    "data.sca.check.compliance.pci_dss": "Payment data standards mapping.",
    "data.sca.check.compliance.tsc": "SOC2 audit category mapping.",
    "data.sca.check.description": "What this system check is about (e.g., password policy).",
    "data.sca.check.id": "Check ID for tracking specific system test.",
    "data.sca.check.previous_result": "What this system check reported last time.",
    "data.sca.check.rationale": "Why this system configuration matters.",
    "data.sca.check.reason": "Why the check failed or passed.",
    "data.sca.check.references": "Documentation links or standards for this check.",
    "data.sca.check.registry": "Registry setting path (Windows-specific).",
    "data.sca.check.remediation": "Suggested fix if the setting is wrong.",
    "data.sca.check.result": "Was this setting compliant? PASS or FAIL.",
    "data.sca.check.title": "Name of the setting or check.",
    "data.sca.description": "Description of the SCA policy.",
    "data.sca.failed": "Number of failed tests.",
    "data.sca.file": "File being assessed.",
    "data.sca.invalid": "Invalid checks during the scan.",
    "data.sca.passed": "Checks that passed.",
    "data.sca.policy": "Name of the policy used.",
    "data.sca.policy_id": "ID of the scan policy.",
    "data.sca.scan_id": "Scan session ID.",
    "data.sca.score": "Compliance score (percentage).",
    "data.sca.total_checks": "Number of tests performed.",
    "data.sca.type": "Type of SCA (e.g., CIS benchmark).",

    # SYSHECK / FILE INTEGRITY MONITORING
    "syscheck.path": "Path to the file or folder being monitored.",
    "syscheck.event": "Type of change: added, deleted, modified.",
    "syscheck.size_after": "New file size.",
    "syscheck.size_before": "Previous file size.",
    "syscheck.md5_after": "New MD5 hash (file content fingerprint).",
    "syscheck.md5_before": "Previous MD5 hash.",
    "syscheck.sha1_after": "SHA1 hash after change.",
    "syscheck.sha1_before": "SHA1 before change.",
    "syscheck.sha256_after": "SHA256 hash after change.",
    "syscheck.sha256_before": "SHA256 before change.",
    "syscheck.inode_before": "File system inode before change.",
    "syscheck.inode_after": "Inode after change.",
    "syscheck.perm_after": "Permissions after the change.",
    "syscheck.mode": "File mode (rwx bits).",
    "syscheck.uid_after": "User ID after change.",
    "syscheck.gid_after": "Group ID after change.",
    "syscheck.uname_after": "Username who owns the file.",
    "syscheck.gname_after": "Group name that owns the file.",
    "syscheck.changed_attributes": "Which attributes changed (size, hash, perms, etc).",
    "syscheck.mtime_after": "Modified time after change.",
    "syscheck.mtime_before": "Modified time before change.",

    # WINDOWS SYSTEM INFO
    "data.win.system.eventID": "Windows event ID (e.g., 4624 = logon success).",
    "data.win.system.channel": "Windows log channel (System, Security).",
    "data.win.system.message": "System event message details.",
    "data.win.system.computer": "Computer name that reported the event.",
    "data.win.system.severityValue": "Severity like ERROR or WARNING.",
    "data.win.system.providerName": "Name of the system that generated the event.",
    "data.win.system.task": "System task like Logon, Service install, etc.",
    "data.win.system.opcode": "Operation type (low-level).",
    "data.win.system.processID": "Process ID for the event.",
    "data.win.system.threadID": "Thread ID — used in deep forensic timelines.",
    "data.win.system.keywords": "Log filtering tags (not critical).",
    "data.win.system.version": "Log schema version.",
    "data.win.system.systemTime": "Time when system recorded this event.",
    "data.win.system.providerGuid": "GUID of the system log provider.",
    "data.win.system.eventSourceName": "Name of the service or source of the event.",
    "data.win.system.eventRecordID": "Index number of the log event.",
    "data.win.system.level": "Numeric level: 1 (Critical), 2 (Error), 3 (Warn), 4 (Info).",
    "data.win.system.eventType": "Type of Windows event (e.g., audit success).",

    # WINDOWS EVENTDATA
    "data.win.eventdata.commandLine": "Command used — very useful to detect suspicious behavior (e.g., PowerShell payloads).",
    "data.win.eventdata.image": "Full path to the process or binary run.",
    "data.win.eventdata.parentImage": "Path to the parent process that launched this one.",
    "data.win.eventdata.parentCommandLine": "Command used to launch the parent process.",
    "data.win.eventdata.user": "User who ran the command.",
    "data.win.eventdata.logonGuid": "Session identifier. Use to correlate events from same login.",
    "data.win.eventdata.logonId": "Logon session ID — useful for user tracking.",
    "data.win.eventdata.logonType": "Type of logon: 2 = local, 3 = network, 10 = RDP.",
    "data.win.eventdata.hashes": "Hashes of the file involved. Helps with malware ID.",
    "data.win.eventdata.integrityLevel": "Security level of process: low, medium, high.",
    "data.win.eventdata.processGuid": "GUID of the process (unique).",
    "data.win.eventdata.parentProcessGuid": "GUID of parent process.",
    "data.win.eventdata.imagePath": "Image location on disk.",
    "data.win.eventdata.accountName": "Windows username.",
    "data.win.eventdata.authenticationPackageName": "Authentication mechanism (e.g., Kerberos).",
    "data.win.eventdata.serviceName": "Service involved in the event.",
    "data.win.eventdata.fileVersion": "Version of binary file (malware often has fake versions).",
    "data.win.eventdata.messageText": "Windows message content, if logged.",
    "data.win.eventdata.targetObject": "Registry key, file, or object that was accessed.",
    "data.win.eventdata.targetUserName": "Username targeted in the event.",
    "data.win.eventdata.targetDomainName": "Domain of the targeted user.",
    "data.win.eventdata.targetLogonId": "Target's session ID.",
    "data.win.eventdata.parentUser": "User who launched the parent process.",
    "data.win.eventdata.originalFileName": "Original name of the file before renaming.",
    "data.win.eventdata.param1": "Extra parameter captured (used in some log types).",
    "data.win.eventdata.param2": "Another parameter — use only when relevant.",
    "data.win.eventdata.binary": "Whether this event included a binary payload.",

    # MISC
    "GeoInfo": "IP geolocation info from enrichment. Useful for identifying foreign threats.",
    "data.status": "Status of the event (e.g., success, failed).",
    "data.level": "Custom field — may reflect severity (check rule.level instead)."
}

def get_field_explanation(field_name):
    return field_explanations.get(field_name, "No explanation available for this field yet.")
